# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz', models.CharField(blank=True, db_column='BIZ', max_length=255, null=True)),
                ('abstract', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('wechat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('actype_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actype_id', models.IntegerField(blank=True, null=True)),
                ('actype_nm', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'account_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('article_type_id', models.IntegerField(blank=True, null=True)),
                ('biz', models.CharField(blank=True, db_column='BIZ', max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('sub_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type_id', models.IntegerField(blank=True, null=True)),
                ('article_type_nm', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'article_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.IntegerField()),
                ('sub_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('is_add', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarnArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('biz', models.CharField(blank=True, db_column='BIZ', max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('warning_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'warn_article',
                'managed': False,
            },
        ),
    ]
